# -*- coding: utf-8 -*-
"""Datedifference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jz-lPe1v8shsACUOKFgueZuaaMW9a6vy
"""

import pandas as pd
data = {
    'vendor': ['Vendor A', 'Vendor A', 'Vendor B', 'Vendor B', 'Vendor C', 'Vendor C','Vendor C', 'Vendor C'],
    'date': ['2024-03-19', '2024-03-17', '2024-03-18', '2024-03-18', '2024-03-17', '2024-03-17','2026-03-17', '2027-03-17'],
    'material': ['Material 1', 'Material 1', 'Material 2', 'Material 2', 'Material 3', 'Material 3','Material 3', 'Material 3'],
    'description': ['Description 1', 'Description 2', 'Description 1', 'Description 2', 'Description 1', 'Description 2','Description 1', 'Description 2'],
    'material_saturation': [0.8, 0.75, 0.9, 0.95, 0.7, 0.65,0.7, 0.65],
    'netprice': [100, 110, 150, 160, 120, 130,120, 130]
}
df = pd.DataFrame(data)
df['date'] = pd.to_datetime(df['date'])
df['date_difference'] = df.groupby(['vendor', 'material', 'description', 'material_saturation', 'netprice'])['date'].transform(lambda x: x.diff())
(df)
filtered_df = df[df['date_difference'].dt.days >= 730]
(filtered_df)